### ISSUE TITLE
Call killed when iOS app goes to background

### ISSUE THREAD

**Issue by KovalovIE** [react-native-webrtc/react-native-webrtc#1084]
Hello everyone!
The problem is when the application goes into the background, the system stops the application after 10-15 seconds (error Message from debugger: Terminated due to signal 9)
This only happens to the one who initiates the call, if you receive a call, it continues in the background.
And it happens on phones IPhone X and below.
Through RNCallKeep I send a signal to the system that the call has started.
Parameters included in UIBackgroundModes - audio, fetch, processing, remote-notification

Any helps?
Can I somehow send a signal to the system that I have an active call?

* **React Native version**: 0.63.4
* **Plugin version**: 1.92.2
* **OS version**: 14.4.2

**Comment by KovalovIE** [comment]
Thanks for your reply!
Right now we're adding voip notifications to the project, but I still can't figure out why my outgoing call ends and my incoming doesn't end in the background?
As I understand it, voip notifications will give a signal to the system, then an incoming call comes in, but what about the outgoing?

**Comment by sagark1510** [comment]
@AurangShah  can you tell me how did you implement the foreground service on android?

**Comment by kiranNegiloni** [comment]
> @AurangShah can you tell me how did you implement the foreground service on android?

Hi @sagark1510 , Did you find a way to implement the foreground service for android?

**Comment by saghul** [comment]
We have not observed crashes due to high CPU usage, but we do throttle framerate indeed.

**Comment by amityadav12239** [comment]
@saghul Facing same issue in iOS,  have you found any solution ?

**Comment by Insta749** [comment]
hi @saghul i was facing same issue, and resolved as well.

In my case, I was using the following code for animation:

<Animatable.View
  duration={1400}
  animation={fadeIn.current}
  easing="ease-in"
  iterationCount="infinite"
  style={styles.bubble}
/>
 
The issue was caused by the infinite animation (iterationCount="infinite"), which caused the app to crash when it went to the background. I handled the issue by stopping the animation when the app enters the background and resuming it when the app becomes active again. Here's how I resolved it:

<Animatable.View
        ref={animatableRef}
         duration={1400}
        animation={fadeIn.current}
	easing="ease-in"
	iterationCount="infinite"
	style={styles.bubble}
/>	
<Animatable.View
  ref={animatableRef}
  duration={1400}
  animation={fadeIn.current}
  easing="ease-in"
  iterationCount="infinite"
  style={styles.bubble}
/>

useEffect(() => {
  const subscription = AppState.addEventListener('change', nextAppState => {
    if (appState.match(/inactive|background/) && nextAppState === 'active') {
      animatableRef.current?.fadeIn();
    } else if (nextAppState === 'background') {
      animatableRef.current?.stopAnimation();
    }
    setAppState(nextAppState);
  });

  return () => {
    subscription?.remove?.();
  };
}, [appState]);
