### ISSUE TITLE
CI supports

### ISSUE THREAD

**Issue by zxcpoiu** [react-native-webrtc/react-native-webrtc#169]
Does anyone has experience with CI can help to add it to this module?

**Comment by davidperrenoud** [comment]
Can the server answer a WebRTC call automatically without a second client? That would be the first step in order to be able to do continuous integration.

For iOS tests, it's pretty easy to get started by using the recording functionality from Xcode:
https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/09-ui_testing.html#//apple_ref/doc/uid/TP40014132-CH13-SW5

Once your integration test is written, you should be able to run it on a service like Travis CI:
https://docs.travis-ci.com/user/languages/objective-c/

**Comment by zxcpoiu** [comment]
@davidperrenoud 

thanks! that's informative.
I think we can have a very basic at the first time --- to pass the build process

by the way,
I thought CI runs on a server, do you mean we can start a mobile simulator first, compile then make call to server which answer the call automatic?

obviously, it's a bit complicate to test on a client-side p2p streaming.
