### ISSUE TITLE
Support for max frame rate?

### ISSUE THREAD

**Issue by thehappycoder** [react-native-webrtc/react-native-webrtc#267]
In our app it's critical to be able to specify maximum frame rate (e.g. 12). It seems react-native-webrtc does not support it at the moment.

Is there some workaround or unofficial branch / fork where this is already implemented? We need this in a week or two.

**Comment by wumke** [comment]
FYI: I've seen articles of people who modify lines of the sdp manually after it has been generated to reduce the bandwidth (see https://webrtchacks.com/limit-webrtc-bandwidth-sdp/)... don't know if it can be fixed this easy though. I noticed that my iphone video stream is displayed very slowly and with lots of delay on my android device, so if limiting the frame rate/dimensions works by modifying te sdp please let me know, then it might also be a solution for me!

**Comment by thehappycoder** [comment]
@wumke The other day I found out that on master branch kRTCMediaConstraintsMinFrameRate is specified https://github.com/oney/react-native-webrtc/blob/master/ios/RCTWebRTC/WebRTCModule%2BRTCMediaStream.m#L45

So I tried specifying kRTCMediaConstraintsMaxFrameRate. It worked. But would be nice to do it via Javascript.

**Comment by wumke** [comment]
@thehappycoder 
Thank you for the hint, you saved me hours of searching and experimenting I had planned for today, I've set the constraints to:
```
NSDictionary *mandatoryConstraints
      = @{ kRTCMediaConstraintsMinWidth     : @"640",
           kRTCMediaConstraintsMinHeight    : @"480",
           kRTCMediaConstraintsMinFrameRate : @"15",
           kRTCMediaConstraintsMaxWidth     : @"1280",
           kRTCMediaConstraintsMaxHeight    : @"720",
           kRTCMediaConstraintsMaxFrameRate : @"30" };
```
Now it works great!

@oney I suggest setting up max values in the repository as long as it is not supported to set them via javascript... imho nobody needs full-hd 60fps video for a video call.

**Comment by zxcpoiu** [comment]
it may needs to align as close as possible with https://www.w3.org/TR/mediacapture-streams/#constrainable-interface if we implement it in javascript api.

for the default value, I'm not sure which default value is ideal for the community.
you better call @saghul

**Comment by saghul** [comment]
> it may needs to align as close as possible with https://www.w3.org/TR/mediacapture-streams/#constrainable-interface if we implement it in javascript api.

Indeed.

> for the default value, I'm not sure which default value is ideal for the community.

The current default is 720p at 30fps. I wouldn't want to look at anything less than that :-)

My line of thinking (I added that default, FWIW) is that it should work great by default. Doing less than 720p is terrible as a first user experience. There is some constraints handling missing on Android IIRC, but they can be tweaked on iOS. Patches for complete constraint handling are more than welcome, but patches attempting to change the defaults will be fought to death by yours truly 😉

**Comment by wumke** [comment]
> Doing less than 720p is terrible as a first user experience.

Maybe, but if for some reason my iPhone (Slo‑mo video support for 1080p at 120 fps and 720p at 240 fps) thinks it should provide the highest possible stream (which is fine by current min constraints) **It does not work at all at the other end (while other apps and libs do)... and that is the worst first user experience you can get!** So I strongly suggest placing some kind of maximum constraints because there are a lot of high end devices with crazy camera's these days, but the major group of users has a midrange device.

**Comment by saghul** [comment]
> Maybe, but if for some reason my iPhone (Slo‑mo video support for 1080p at 120 fps and 720p at 240 fps) thinks it should provide the highest possible stream (which is fine by current min constraints)

What constraints are you passing? We are currently using 720p/30fps as the default.

> It does not work at all at the other end

What is the other end? A browser? The same app?

**Comment by wumke** [comment]
> What constraints are you passing? We are currently using 720p/30fps as the default.

Right nog I'm passing the original min constraints as max constraints... I lowered the min constraints to half the max values. (When the app I'm making is ready I'll start experimenting and gathering user experiences from our testing audience)

> What is the other end? A browser? The same app?

iPhone7 with iOS 10.3 <=> Motorola Moto G (2nd gen) with android v6.0 (older, but still better than some new low-end android devices sold these days. I became a true Motorola fan because of this device and their factory support for new android releases and even root tools and system images!)
The iPhone stream is displayed at about half the normal speed + a couple of seconds delay on the Motorola with the original constraints (=completely unuseable). 

I think this library is great and it would be a shame if people would drop it because of a demo app not working because of some quality constraints...

**Comment by saghul** [comment]
On iOS we don't really apply constraints, we always use the defaults: https://github.com/oney/react-native-webrtc/blob/master/ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m#L271-L272

On Android, however, we do: https://github.com/oney/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L571-L587

If you feel like taking a stab at this I'll gladly help review it.

**Comment by saghul** [comment]
Flexible (and modern) constraints are now supported in master.
