### ISSUE TITLE
addTrack instead of deprecated addStream

### ISSUE THREAD

**Issue by chroth7** [react-native-webrtc/react-native-webrtc#339]
#### Expected behavior
As a webRTC user, I would like to use `addTrack` (as `addStream` is deprecated, see here: https://developer.mozilla.org/de/docs/Web/API/RTCPeerConnection/addStream

#### Observerd behavior
`addStream` does not exist on `peerConnection`.

#### Steps to reproduce the problem

```javascript
// current working version
peerConnection.addStream(stream);
```

```javascript
// expected
const audioTracks = stream.getAudioTracks();
peerConnection.addTrack(audioTracks[0], stream);
```

**Comment by basitsattar** [comment]
Hi, is this issue resolved now?

**Comment by ibc** [comment]
@basitsattar you can help with a PR.

**Comment by ajnozari** [comment]
So safari on both IOS and macOS have dropped addstream support.  I’m looking into a fix but I’m not really sure how to move forward with adding add track and ontrack which is what we need.  

Any points in the right direction would be appreciated.

**Comment by saghul** [comment]
@ajnozari Is you are using this plugin you are not using Safari, so that shouldn't matter.

**Comment by ajnozari** [comment]
@saghul I think you're misunderstanding me.  

What I mean is when a client using this package (on a phone), makes a call with someone using macOS with safari 12.0.0 and higher the call cannot be completed.  SAFARI has removed (completely) `addstream` and `onaddstream`. They are depreciated in most browsers and will probably be removed sooner rather than later.

This means that anyone using this package can no longer make calls with people using Safari 12 and higher.

This needs to be addressed and I'm trying to add in addtrack and ontrack to RTCPeerConnection, but I'm not 100% sure how to go about doing this but it is needed as more and more browsers will drop support.  If anyone could even point me in the right direct towards adding this to the package I would do so and submit a PR.

This is an active open issue that is only getting worse a year later.

**Comment by ibc** [comment]
Whether the browser JS uses the new track based API or the super old and boring and legacy stream based API (as react-native-webrtc does and will do for many years) is irrelevant. Nobody forces you to use the same JS logic in both sides of the "call".

**Comment by ajnozari** [comment]
@ibc then I must be missing something because this didn't work properly when I tried with my front-end developer.  Does this mean we just need to implement platform specific code (addstream/addtrack depending on support) and it won't care as long as the resulting streams that are sent are valid?

**Comment by ibc** [comment]
Yes. Each side may need to use a different API to work. In the Safari side you can use modern WebRTC 1.0 API. In the react-native-webrtc side, go to 2013.

**Comment by saghul** [comment]
@ibc I'm sick and tired of your snide remarks regarding this. This is your last working or I'll have to block you from this project.

**Comment by ibc** [comment]
@saghul, considering the lack of project [documentation](https://react-native-webrtc.discourse.group/t/api-documentation/146) I think (joking apart) that I've given a proper response in this issue, probably better than redirecting to the "RTCPeerConnection" documentation in MDN as the project's README does (which obviously does not match the JS API exposed by this lib).

**Comment by saghul** [comment]
Please follow: https://github.com/react-native-webrtc/react-native-webrtc/issues/1005
