### ISSUE TITLE
[QUESTION] How to handle internet connection change in CALLEE side.

### ISSUE THREAD

**Issue by RZulfikri** [react-native-webrtc/react-native-webrtc#543]
Hi, I have a problem in changing connection between wifi to mobile data and vice versa.
it's fine on caller side, but when callee change connection, it does not want to connect. and i have this error message on caller side :

```
"PeerConnection cannot create an answer in a state other than have-remote-offer or have-local-pranswer."
```
then i'm adding condition before `createAnswer` funtion and check the signaling state `if (pc.signalingState === ' have-remote-offer' || pc.singalingState === 'have-local-pranswe')`

then I got other error message.

```
"Failed to set remote answer sdp: Called in wrong state: kStable"
```

then I add condtion before `setRemoteDescription` function and check signaling state  `if (pc.signalingState === 'have-local-offer')`

then i got other error message in calleee side.

```
Error at create answer PeerConnection cannot create an answer in a state other than have-remote-offer or have-local-pranswer
```

Can someone help me to understand this error message, what should i do to handle this ?

Thank you..

**Comment by 8BallBomBom** [comment]
The way we are handing this is by checking if the connection drops then performing an ice restart.
Pretty much repeating the whole call process without having to grab devices and without having to accept the call again.

**Comment by RZulfikri** [comment]
@8BallBomBom which side call ice restart ? the calle or caller ?
Actually I already implement this condition.

when calle disconect, it will send message to signaling to tell caller do ice restart, then i got that error message.

can you advice me, how did you call or implement ice restart. ?

in my case, if caller change connection ice restart works then can connect, but if callee change connection it cannot connect.

**Comment by 8BallBomBom** [comment]
Pretty much we have ice restart implemented on the caller side.
Both ends detect disconnection and then go into renegotiation where we have the call screen show an attempting to reconnect message.
But while that is happening the caller sends out a new call request which then sits on the backend or gets delivered instantly if the callee is connected to the backend.
So pretty much the callee pings to the backend for the new offer constantly unless already connected.
Which then once the new offers received just triggers the call to restart but instead of holding onto the offer and waiting for the user to accept it just skips over the whole acceptance process.

As for how we call ice restart?
Pretty much adding iceRestart into the offer options set as true when running createOffer.

**Comment by RZulfikri** [comment]
@8BallBomBom hmmm, I think I have implement that too. have you facing that issue / error message ?
and can you show me a bit, how did you handle the local_description and ice_candidate ? did you check the signalingState ? and what did you do on iceCandidateState ?

**Comment by 8BallBomBom** [comment]
I'm not facing the issue at all no.
The way we are handing it isn't out of the usual.
Theres simple checks on if the iceCandidateState goes to failed or if it gets stuck checking for too long which then triggers the iceRestart.
As for the signalingState? we don't have anything to do with this checking that.
Pretty much just listeners for connectivity changes which then in itself work towards triggering an iceRestart.

**Comment by saghul** [comment]
The forum is a better place to continue the discussion if need be.

**Comment by michtt99** [comment]
Same issue (
When I switch from Wi-Fi to 3G, the call is successfully restored (if the call was initiated with Wi-Fi active and 3G enabled).
However, if the call is made over Wi-Fi, and then Wi-Fi is turned off and only 3G is enabled, the connection is no longer restored.
