### ISSUE TITLE
Help, Weird thing is happening

### ISSUE THREAD

**Issue by skokonxd** [react-native-webrtc/react-native-webrtc#889]
Hello, I’m using WebRTC ^1.75.3

The problem i have is when i keep the app running and switch to another app and user joins the call, connection is not sucess, we don't hear each other, but when there is already one user, me and another user in a call and i go switch to another app and the third user joins it just works without any problem

Also if I’m in app it works even if I'm alone in the call.

**Comment by ajnozari** [comment]
This sounds like an sdp/call negotiation issue. Are you assigning each new person their own id or are you replacing the caller?

**Comment by skokonxd** [comment]
> This sounds like an sdp/call negotiation issue. Are you assigning each new person their own id or are you replacing the caller?

no i assign each new person their own id

**Comment by ajnozari** [comment]
It looks like it’s a background issue.  The app isn’t negotiating while it’s in the background, despite being active due to the call. I’m almost at the same point in the app I’m working on give me a few days to poke this more as I think I’ve dealt with it in the past, I just can’t remember of the top of my head how.
