### ISSUE TITLE
iOS 'WebRTC/RTCMediaStreamTrack.h' file not found

### ISSUE THREAD

**Issue by rodneyrehm** [react-native-webrtc/react-native-webrtc#920]
#### Expected behavior

application compiles

#### Observed behavior

```
$ set -o pipefail && xcodebuild -workspace Daedalus.xcworkspace -scheme Daedalus -configuration Automation -derivedDataPath ./simulator -sdk 'iphonesimulator' -destination 'generic/platform=iOS Simulator' build | xcpretty

…

▸ Compiling RTCMediaStreamTrack+React.m

❌  /…/node_modules/react-native-webrtc/ios/RCTWebRTC/RTCMediaStreamTrack+React.h:2:9: 'WebRTC/RTCMediaStreamTrack.h' file not found

#import <WebRTC/RTCMediaStreamTrack.h>
                  ~~^

…

The following build commands failed:
	CompileC /…/ios/simulator/Build/Intermediates.noindex/Pods.build/Automation-iphonesimulator/react-native-webrtc.build/Objects-normal/x86_64/RTCMediaStreamTrack+React.o /…/node_modules/react-native-webrtc/ios/RCTWebRTC/RTCMediaStreamTrack+React.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
[11:51:04]: Exit status: 65
```

#### Steps to reproduce the problem

Upgraded from `1.84.0` to `1.87.2`. After installing through npm and running pod install my build failed with `'WebRTC/RTCDefaultVideoDecoderFactory.h' file not found`. From https://github.com/react-native-webrtc/react-native-webrtc/issues/906 I got the idea to have pod install re-create the `[CP] Embed Pods Frameworks` task (by removing the existing task from `project.pbxproj` and running pod install again, producing the following in `project.pbxproj`:

```
/* Begin PBXNativeTarget section */
13B07F861A680F5B00A75B9A /* MyAppName */ = {
  isa = PBXNativeTarget;
  buildConfigurationList = 13B07F931A680F5B00A75B9A /* Build configuration list for PBXNativeTarget "MyAppName" */;
  buildPhases = (
    08A4A3CD28434E44B6B9DE2E /* [CP] Check Pods Manifest.lock */,
    FD10A7F022414F080027D42C /* Start Packager */,
    13B07F871A680F5B00A75B9A /* Sources */,
    13B07F8C1A680F5B00A75B9A /* Frameworks */,
    13B07F8E1A680F5B00A75B9A /* Resources */,
    00DD1BFF1BD5951E006B06BC /* Bundle React Native code and images */,
    800E24972A6A228C8D4807E9 /* [CP] Copy Pods Resources */,
    F5ACD7A95F158C4974EA1AC7 /* [CP-User] [RNFB] Core Configuration */,
    2B5CA7865D2EB811579FD7BE /* [CP] Embed Pods Frameworks */,
  );
  buildRules = (
  );
  dependencies = (
  );
  name = MyAppName;
  productName = MyAppName;
  productReference = 13B07F961A680F5B00A75B9A /* MyAppName.app */;
  productType = "com.apple.product-type.application";
};
/* End PBXNativeTarget section */

2B5CA7865D2EB811579FD7BE /* [CP] Embed Pods Frameworks */ = {
  isa = PBXShellScriptBuildPhase;
  buildActionMask = 2147483647;
  files = (
  );
  inputPaths = (
    "${PODS_ROOT}/Target Support Files/Pods-MyAppName/Pods-MyAppName-frameworks.sh",
    "${PODS_XCFRAMEWORKS_BUILD_DIR}/WebRTC/WebRTC.framework/WebRTC",
  );
  name = "[CP] Embed Pods Frameworks";
  outputPaths = (
    "${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/WebRTC.framework",
  );
  runOnlyForDeploymentPostprocessing = 0;
  shellPath = /bin/sh;
  shellScript = "\"${PODS_ROOT}/Target Support Files/Pods-MyAppName/Pods-MyAppName-frameworks.sh\"\n";
  showEnvVarsInLog = 0;
};
```

#### Platform information

* **React Native version**: 0.63.4
* **Plugin version**: 1.87.2
* **Xcode**: 12.3
* **cocoapods**: 1.10.0

**Comment by ksitko** [comment]
Same issue using here with pods version `1.10.1`. I've tried cleaning node_modules, cleaning pods and their cache. Still same error.

**Comment by saghul** [comment]
Can you reproduce the problem with the sample app?

**Comment by leeeomaaax** [comment]
I was facing kind of the same issue and finally managed to solve it, although I'm not yet clear what specifically was causing the build to fail.

The difference was that, in my case, build was failing only for the **Release** variant and the architecture missing was the **armv7** instead of the x86_84.

Our fix:
1. update podfile and force react-native-webrtc to build only for the desired architecture using EXCLUDED_ARCHS config.
forcing ONLY_ACTIVE_ARCH and IPHONEOS_DEPLOYMENT_TARGET were also necessary to make the build succeed, but I would start with the EXCLUDED_ARCHS config
```
      target.build_configurations.each do |config|
        if config.name != 'Debug'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
          if target.name == "react-native-webrtc"
            config.build_settings["EXCLUDED_ARCHS"] = "armv7"
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
          end
        end
      end
    end
```
This phrase from [this thread](https://www.cnblogs.com/maxwelldzl/p/13810575.html) led me to this solution.
"You have to do the same for the Pod project until all the cocoa pod vendors are done adding following in their Podspec."
My hypothesis is that one of our other dependencies was causing the whole project to build for the armv7 arch.

2. disable bitcode

3. in your Info.plist, make sure 
```
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>arm64</string>
	</array>

```

4. For developing locally, archs in project.pbxproj should be set to **ARCHS = "$(ARCHS_STANDARD)";**
5. For building the release, archs in project.pbxproj should be set to **ARCHS = arm64;**
(keeping the release arch different from our debug arch was causing cocoapods to fail to install/update. Solution can be found [here](https://github.com/CocoaPods/CocoaPods/issues/10138)


Other links that were helpful in some way:
https://developer.apple.com/forums/thread/656509
https://github.com/CocoaPods/CocoaPods/issues/7161
https://developer.apple.com/forums/thread/90582
https://dengweijun.com/2020/09/08/Ensure-that-app-executables-and-bundled-frameworks-use-consistent-architectures/
https://crunchybagel.com/solving-the-itunes-connect-itms-90502-uirequireddevicecapabilities-error/

**Comment by saghul** [comment]
> the architecture missing was the **armv7**

We no longer provide that architecture since iOS 10 devicecs are no longer supported and there is no armv7 device with iOS > 10.
