### ISSUE TITLE
Can't get h264 in SDP offer from Android phones

### ISSUE THREAD

**Issue by eggysplat** [react-native-webrtc/react-native-webrtc#983]
I'm currently trying to use Janus as a media gateway for a video calling app. I would like to use a codec for the VideoRoom plugin that is commonly supported between iOS / Android / Web and found that h264 (with cbp) seems to be the most viable option.

However, when trying to publish a stream with Android and creating an SDP offer, the SDP only contains offers of VP8 and VP9 video codecs. There is no mention of h264 at all.

I've tried this with:

- Nokia 3 (which I understand **might** not be supported as it is a MediaTek SoC
- Fairphone 3 (which should have h/w support as it's a Qualcomm SoC)
- Pixel 3 from Android Studio (not sure if this would simulate h/w support or no)

On each device, the SDP is similar to the following:

```
v=0
o=- 3005012469418028420 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE video
a=msid-semantic: WMS b0164d43-a6ed-4ea6-aa6a-b2159930e157
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:4a3Z
a=ice-pwd:2OPz/YOb4EyM/KK4KXxAwOFy
a=ice-options:trickle renomination
a=fingerprint:sha-256 9E:57:56:62:B4:92:77:54:8D:FB:57:CC:F1:C2:D1:41:BB:65:93:94:B0:AC:86:CF:4F:85:8B:70:E8:EB:F2:92
a=setup:actpass
a=mid:video
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 red/90000
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 ulpfec/90000
a=ssrc-group:FID 2956772981 3082773025
a=ssrc:2956772981 cname:XZGzaNFhbDJwWlzH
a=ssrc:2956772981 msid:b0164d43-a6ed-4ea6-aa6a-b2159930e157 486c0554-7527-472f-b098-fbbb895e1914
a=ssrc:2956772981 mslabel:b0164d43-a6ed-4ea6-aa6a-b2159930e157
a=ssrc:2956772981 label:486c0554-7527-472f-b098-fbbb895e1914
a=ssrc:3082773025 cname:XZGzaNFhbDJwWlzH
a=ssrc:3082773025 msid:b0164d43-a6ed-4ea6-aa6a-b2159930e157 486c0554-7527-472f-b098-fbbb895e1914
a=ssrc:3082773025 mslabel:b0164d43-a6ed-4ea6-aa6a-b2159930e157
a=ssrc:3082773025 label:486c0554-7527-472f-b098-fbbb895e1914
```

Other clients (Web / iOS) are connecting using h264 with no issue. The h264 stream is being sent to the Android client and it can receive / display it with no issue, it just refuses to offer it in the SDP.

Is there anything that I need to do to have this enabled in the offer?

#### Steps to reproduce the problem

In Janus, I have created the videoroom with "videocodec": "h264" and "h264_profile": "42e01f". When publishing, I am using the following code

```
                console.log("Getting local video")
                let videoStream = await getMediaVideo(); // returns a MediaStream object containing audio / video (tried just video)
                console.log("Got local video", videoStream);
                localVideoPeer.current = new NativePeerConnection();

                await localVideoPeer.current.setInputStream(videoStream);
                console.log("Set the local stream as an input to localVideoPeer");

                const sdp = await localVideoPeer.current.createOffer();
                console.log("Created offer", sdp);
                let resp = await video.publish({ jsep: { type: "offer", sdp }, display: "video", video: true, audio: true, videocodec: "h264" }) as VideoRoomTypes.PublisherPublishResponse;
```

NativePeerConnection above is just a wrapper class for the react-native-webrtc PeerConnection with some helper functions.

#### Platform information

* **React Native version**: 0.63.3
* **Plugin version**: 1.89.1
* **OS**: Android
* **OS version**: 9 (and 10)

**Comment by saghul** [comment]
We don't do any codec selection, just use what WebRTC provides by default. https://github.com/react-native-webrtc/react-native-webrtc/blob/4780ef586c1a6f4e7de797db60ca33093358b1b8/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L122

**Comment by guying18** [comment]
I think the problem is that Webrtc's builtin VideoEncoder.

[DefaultVideoEncoder](https://chromium.googlesource.com/external/webrtc/+/HEAD/sdk/android/api/org/webrtc/DefaultVideoEncoderFactory.java)
is just a combile of [HardwareVideoEncoderFactory](https://chromium.googlesource.com/external/webrtc/+/HEAD/sdk/android/api/org/webrtc/HardwareVideoEncoderFactory.java) and [SoftwareVideoEncoderFactory](https://chromium.googlesource.com/external/webrtc/+/HEAD/sdk/android/api/org/webrtc/SoftwareVideoEncoderFactory.java).

And h264 is included only when `HardwareVideoEncoderFactory.getSupportedCodecs` return 'h264`.

In SoftwareVideoEncoderFactory, getSupportedCodecs return `vp8, vp9, av1`

And when you look into the implementation of `isHardwareSupportedInCurrentSdkH264`, it tells that h264 is only supported on part of Qcom / Exynos chiplets, which is not correct.

I suggest you copy & paste the `HardwareVideoEncoderFactory` code, and make anthoer class with your own `isHardwareSupportedInCurrentSdkH264` method, use that class as your own `encoderFactory`.

https://github.com/react-native-webrtc/react-native-webrtc/blob/4780ef586c1a6f4e7de797db60ca33093358b1b8/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L122

**Comment by t9-jlee** [comment]
I've been tackling the same problem recently, I was able to find a way to fix it with reference to @guying18's comment above, by creating a patch with patch-package

the file is react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java lines 83-89

```
// if (eglContext != null) {
//     encoderFactory = new H264AndSoftwareVideoEncoderFactory(eglContext);
//     decoderFactory = new H264AndSoftwareVideoDecoderFactory(eglContext);
// } else {
        encoderFactory = new SoftwareVideoEncoderFactory();
        decoderFactory = new SoftwareVideoDecoderFactory();
// }
```

by commenting out the if else statement it forces the program it to use the SoftwareVideoEncoder/DecoderFactory, I was able to turn the black video back to normal.

hope this helps who ever might be struggling with this because it took me a while.

**Comment by saghul** [comment]
On Android >= 29 WebRTC will rely on the system telling if the HW encoder works. Looks like your system might not be working correctly.




> And when you look into the implementation of `isHardwareSupportedInCurrentSdkH264`, it tells that h264 is only supported on part of Qcom / Exynos chiplets, which is not correct.

This is only the case for Android < 29.

**Comment by besimesadi** [comment]
> I've been tackling the same problem recently, I was able to find a way to fix it with reference to @guying18's comment above, by creating a patch with patch-package for react-native-webrtc@118.0.7
> 
> the file is react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java lines 83-89
> 
> ```
> // if (eglContext != null) {
> //     encoderFactory = new H264AndSoftwareVideoEncoderFactory(eglContext);
> //     decoderFactory = new H264AndSoftwareVideoDecoderFactory(eglContext);
> // } else {
>         encoderFactory = new SoftwareVideoEncoderFactory();
>         decoderFactory = new SoftwareVideoDecoderFactory();
> // }
> ```
> 
> by commenting out the if else statement it forces the program it to use the SoftwareVideoEncoder/DecoderFactory, I was able to turn the black video back to normal.
> 
> hope this helps who ever might be struggling with this because it took me a while.

I'm encountering a similar issue with H.264 on iOS. Has anyone found a solution or workaround for iOS devices?
The offer I receive includes H.264, but my answer SDP does not include it.
Any guidance or pointers would be greatly appreciated.
